export const purseImages = [
  "purse1.jpeg",
  "purse2.jpeg",
  "purse3.jpeg",
  "purse4.jpeg",
  "purse5.jpeg",
  "purse6.jpeg",
  "purse7.jpeg",
  "purse8.jpeg",
  "purse9.jpeg",
  "purse10.jpeg",
  "purse11.jpeg",
  "purse12.jpeg",
  "purse13.jpeg",
  "purse14.jpeg",
  "purse15.jpeg",
  "purse16.jpeg",
  "purse17.jpeg",
  "purse18.jpeg",
  "purse19.jpeg",
  "purse20.jpeg",
  "purse21.jpeg",
];

export const jewelryImages = [
  "beadedbracelet.jpg",
  "brace8.jpeg",
  "brace9.jpeg",
  "brace10.jpeg",
  "brace11.jpeg",
  "brace12.jpeg",
  "brace13.jpeg",
  "brace14.jpeg",
  "bracelet2.jpg",
  "braceletChanel.jpg",
  "braceletgold.jpeg",
  "braclet.jpg",
  "chanelNecklace.jpg",
  "crown.JPG",
  "gB1.jpg",
  "gB2.jpg",
  "gb3.jpg",
  "gB4.jpg",
  "glassBangles.jpg",
  "gN1.JPG",
  "gN2.JPG",
  "gN3.JPG",
  "gN4.JPG",
  "gN5.JPG",
  "gN6.jpg",
  "goldBangles.jpg",
  "goldChain.jpg",
  "goldTwisted.jpg",
  "gR1.jpg",
  "gW1.jpg",
  "mensRing.jpg",
  "mensBraclet.jpg",
  "metalChoker.jpg",
  "multiChain.jpg",
  "MultiNecklaces.jpg",
  "necklace.jpg",
  "necklace2.jpg",
  "PearlNeaclace.jpg",
  "pink_ring.jpg",
  "purpleRing.jpg",
  "ring.jpg",
  "skullEarrings.jpg",
  "skullPendant.jpg",
  "skullRing.jpg",
  "skullWatch.jpg",
  "tarina.jpg",
  "texturizedPink.jpg",
  "thickGoldchain.jpg",
  "watch1.jpg",
  "weddingRings.jpg",
  "white3Karat.jpg",
  "whiteBangles.jpg",
  "womansWedding.jpg",
  "wRing.jpg",
];

export const brands = 
[
  "Cuyana",
  "Bag Heritage",
  "Michael Kors",
  "Juicy Corture",
  "Prada",
  "Chanel",
  "Gucci",
  "Gucci",
  "Prada",
  "Dior",
  "Louis Vuitton",
  "Hermès",
  "Armani",
  "Calvin Klein",
  "Fendi",
  "Versace",
];
// [ "Bulgari", "Cartier", "Gorjana", "King Baby", "Missoma", "Swarovski"]
 

export const madeOf =  ["leather", "vegan leather", "other"];
//  [ "14K", "18K", "platinum"]


export const purseDescriptions = [
  "An impeccable blend of sumptuous leather and timeless elegance, this purse promises to become the centerpiece of any sophisticated wardrobe",
  "Crafted with the finest craftsmanship, this versatile tote showcases a subtle sheen that effortlessly complements both casual and formal ensembles",
  "Exuding understated luxury, this handbag boasts a supple, richly colored material that feels as exquisite as it looks, perfect for the discerning fashionista",
  "Designed to inspire confidence, this stylish accessory features a sleek silhouette and a gentle shine that turns every outing into a runway moment",
  "Elevate your everyday style with this luxurious tote, whose refined texture and graceful proportions echo the elegance of classic design",
  "With a harmonious blend of durability and beauty, this tote’s premium material and clean lines make it a timeless investment for any fashion aficionado",
  "An epitome of contemporary chic, this handbag presents a glossy finish and subtle detailing that exudes confidence and refined allure",
  "Embrace effortless sophistication with this tote’s polished surface and elegant shape, crafted to be both practical and irresistibly chic",
  "Infused with a hint of glamour, this bag’s high‑quality material offers a gentle luster that reflects the wearer’s impeccable taste and style",
  "Unleash your inner diva with this plush purse, whose luxurious texture and graceful design are engineered to capture admiration wherever you go",
  "Showcase your unique flair with this impeccable tote, whose refined finish and flattering shape create an air of effortless sophistication",
  "An essential piece of high‑end style, this purse’s superior material and streamlined silhouette effortlessly marry functionality with glamorous appeal",
  "Designed for the modern icon, this tote offers a subtle yet striking sheen and an unmistakable aura of confidence in every glance",
  "Crafted for those who desire a statement of refinement, this purse’s luxurious material and graceful proportions stand out as a testament to chic elegance",
  "Make a lasting impression with this elegant tote, whose premium texture, minimalist design, and sophisticated flair make it the ultimate accessory for style‑savvy individuals",
];

export const jewelryDescriptions = [
  "An iconic treasure that combines radiant diamonds with a gleaming metal frame, designed to illuminate every cherished moment",
  "Gracefully engineered, this piece showcases a cascade of sparkling stones set in refined metal, making it a timeless heirloom for the discerning wearer",
  "Infused with luxury, this design features a stunning diamond display that captivates from every angle, perfect for those who crave lasting elegance",
  "With a flawless blend of fine metal and brilliant gems, this creation offers an unforgettable allure that celebrates the art of fine jewelry",
  "Elevate your style with this masterpiece, where a generous array of diamonds rests on a supple metal band, exuding sophistication in every glance",
  "An expression of pure opulence, this piece boasts a captivating diamond array set in a meticulously crafted metal frame, destined to become a treasured legacy",
  "Designed for the modern collector, this piece pairs a radiant diamond scatter with elegant metalwork, creating a statement that stands out in any setting",
  "An embodiment of refined beauty, this piece highlights a stunning diamond arrangement against a polished metal backdrop, celebrating timeless glamour",
  "With meticulous attention to detail, this design offers a bold diamond sparkle set in a sleek metal band, promising an unforgettable statement of luxury",
  "Crafted for those who value distinction, this piece features a striking diamond cluster that shines against a subtle metal base, echoing classic sophistication",
  "An exceptional jewel that marries a generous diamond display with fine metal craftsmanship, offering an alluring blend of sparkle and refined elegance",
  "Designed to inspire awe, this piece showcases an impressive diamond scatter that catches the light in a way that is both bold and effortlessly refined",
  "With its radiant gemstone setting and smooth metal contour, this design delivers an enchanting fusion of sparkle and elegance for the jewelry enthusiast",
  "Exuding contemporary charm, this piece features a dazzling diamond collection encased in a polished metal frame, perfect for those who appreciate enduring luxury",
  "An exquisite creation that balances a lavish diamond display with sleek metal detailing, creating a statement that effortlessly conveys confidence and grace",
  "An elegant treasure that glows with a generous scatter of diamond sparkle, this piece captures the essence of timeless luxury for the discerning jewelry aficionado",
  "Radiant in gold and platinum, this masterpiece showcases a brilliant diamond setting that promises to elevate any occasion into an unforgettable celebration",
  "A captivating statement that marries the warmth of gold with the subtlety of platinum, adorned with dazzling diamonds that whisper stories of opulence",
  "Crafted for those who cherish unparalleled elegance, this exquisite design features a cascade of fine diamonds, perfect for the jewelry lover in your life",
  "Delicately balanced between gold and platinum, this stunning creation boasts an impressive diamond display that turns every glance into a moment of awe",
  "An unforgettable piece that celebrates the union of precious metals and flawless diamonds, designed to shine as the centerpiece of any ensemble",
  "Exuding sheer sophistication, this refined piece is finished with sparkling diamonds, ensuring it remains a lasting icon of indulgence and style",
  "Designed for the modern collector, this remarkable item blends gold with platinum in a seamless harmony, highlighted by a generous spread of dazzling diamonds",
  "With a striking blend of gold and platinum, this unique piece is infused with sparkling diamonds, creating a bold statement that commands attention",
  "Perfect for those who value grandeur, this exceptional creation showcases a luminous diamond array set against the classic elegance of gold and platinum",
  "An unparalleled jewel that marries the richness of gold and platinum with the allure of fine diamonds, destined to become a cherished family heirloom",
  "Exquisite craftsmanship meets dazzling brilliance in this design, where a captivating diamond collection meets the timeless beauty of gold and platinum",
  "A masterpiece that embodies true luxury, featuring a breathtaking diamond scatter atop a luxurious gold-platinum fusion, tailored for the ultimate statement wearer",
  "An iconic treasure that balances the warmth of gold with the allure of platinum, accented by an enchanting array of diamonds, crafted for unforgettable moments",
];

export const purseReviews = [
  "The bag's sturdy stitching gives me confidence that it will withstand daily wear without fraying.",
  "I love how the interior compartments keep my essentials neatly organized, even when I'm on the go.",
  "The handle feels balanced and comfortable, making it easy to carry for hours.",
  "The lightweight design surprised me—it's surprisingly durable for its size.",
  "The zipper glides smoothly, and the pull stays in place even after frequent use.",
  "The material feels smooth yet resilient, a testament to its high quality.",
  "I've carried it through a weekend trip, and it still looks like new.",
  "The subtle texture adds a touch of elegance without being ostentatious.",
  "The compact size is perfect for a minimalist wardrobe, yet it holds everything I need.",
  "The hidden pockets are a lifesaver for quick access to my phone and keys.",
  "The bag's silhouette stays true, even after prolonged handling.",
  "Its neutral finish complements any outfit, which is great for versatile styling.",
  "The strap is reinforced, preventing any sagging over time.",
  "The design includes a convenient key loop, which keeps my keys from getting lost.",
  "The overall construction feels robust, and I've seen no signs of wear after months.",
  "The bag's interior is lined with a durable fabric that resists stains.",
  "I appreciate the thoughtful placement of a smaller pocket for my wallet.",
  "The bag's proportions are flattering and functional at the same time.",
  "The craftsmanship is evident in every seam, providing a sense of security.",
  "I have had no trouble with the bag's closure, even after heavy use.",
  "The subtle embossing adds a refined detail without compromising durability.",
  "The bag retains its shape well, resisting compression from daily use.",
  "It’s easy to clean—just a quick wipe and it's as good as new.",
  "The bag's size is just right for a minimalist wardrobe, yet it holds everything I need.",
  "The handle feels balanced and comfortable, making it easy to carry for hours.",
  "The bag's design includes a convenient key loop, which keeps my keys from getting lost.",
  "The bag’s interior is lined with a durable fabric that resists stains.",
  "I love the practicality of the hidden pockets for quick access to essentials.",
  "The bag’s structure feels robust, with no signs of fraying after months of use.",
  "The zipper is smooth and the pull stays in place, even after frequent use.",
  "The bag's neutral finish complements any outfit, making it versatile.",
  "The reinforced strap prevents sagging, even when carrying heavy items.",
  "The subtle texture adds elegance without compromising durability.",
  "The bag holds its shape well, resisting compression over time.",
  "The inner lining is durable and easy to clean.",
  "I appreciate the thoughtfully placed pocket for my wallet.",
  "The bag’s proportions are flattering and functional.",
  "The overall construction feels robust, indicating excellent build quality.",
  "The bag's closure remains secure after frequent use.",
  "The subtle embossing adds a refined detail without compromising durability.",
  "The bag retains its shape well, resisting compression from daily use.",
  "The bag is surprisingly lightweight yet surprisingly durable for its size.",
  "The bag is easy to clean—just a quick wipe and it's as good as new.",
  "The bag’s design is functional, yet stylish, making it suitable for any setting.",
  "The bag has proven to be reliable on a weekend trip, looking as good as new.",
  "The handle is balanced and comfortable, making it easy to carry for hours.",
  "The zipper glides smoothly and stays in place.",
  "The material feels smooth yet resilient.",
  "Durability is evident, even after months of use.",
  "Storage is well thought out, keeping my essentials organized.",
  "Overall, the bag delivers on both style and function.",
  "The bag is sturdy and dependable, making it a dependable choice.",
  "The design provides ample space without feeling bulky.",
  "The bag’s construction feels solid, with no signs of wear after frequent use.",
  "The hidden pockets add convenience and are easy to reach.",
  "The bag’s proportions are perfect for everyday use.",
  "The craftsmanship ensures every seam feels secure and durable.",
  "The bag retains its shape after prolonged handling.",
  "The bag is versatile, fitting into a minimalist wardrobe without compromising capacity.",
  "The key loop is practical, keeping keys from getting lost.",
  "The bag’s interior is lined with durable material that resists stains.",
  "The bag’s overall structure is robust and reliable.",
  "The bag offers thoughtful storage options for quick access to essentials.",
  "The bag’s design strikes a balance between elegance and practicality.",
  "The bag’s sturdy build offers confidence for daily wear.",
  "The bag’s functional design enhances everyday organization.",
  "The bag is durable and has shown no signs of wear over time.",
];

export const jewelryReviews = [
  "The finish is flawless, giving a polished look that lasts through everyday wear.",
  "The lightweight feel ensures comfort, even after a full day of use.",
  "It balances style and practicality, making it a versatile addition to any outfit.",
  "The meticulous craftsmanship shines, reflecting light without ever tarnishing.",
  "It's designed for durability, with no signs of wear after months of routine use.",
  "The sleek silhouette blends effortlessly with both casual and formal attire.",
  "It fits perfectly, staying secure without leaving any discomfort.",
  "The subtle sheen catches the eye, yet remains understated and sophisticated.",
  "The design feels seamless, enhancing the natural beauty of any ensemble.",
  "Its robust construction offers confidence for daily adventures.",
  "The lightweight nature guarantees ease of wear, no matter the occasion.",
  "Every detail is carefully executed, delivering timeless elegance.",
  "The piece stays true to shape, resisting everyday wear and tear.",
  "It's surprisingly resilient, maintaining its luster through countless days.",
  "The comfort level is excellent, leaving no feeling of heaviness.",
  "The understated brilliance adds a touch of refinement to any look.",
  "It adapts to any style, whether dressed up or kept casual.",
  "The craftsmanship is evident, with a smooth surface that feels reassuring.",
  "It's made to endure, offering lasting quality without compromising style.",
  "The subtle sparkle highlights a refined design without overwhelming.",
  "Designed for comfort, it feels almost invisible on the skin.",
  "Every aspect feels intentional, enhancing confidence in its enduring quality.",
  "The piece retains its allure, even after prolonged daily wear.",
  "The design is crafted for longevity, never losing its polished appeal.",
  "Its form feels balanced, making it an effortless accessory for any setting.",
  "The gentle glow invites admiration while remaining unobtrusive.",
  "Built to last, it delivers a lasting impression of quality.",
  "The delicate lines blend with both classic and contemporary fashions.",
  "Crafted with precision, it offers a seamless fit for everyday use.",
  "Elegant yet enduring, it holds its charm through countless moments.",
  "The subtle luster catches the light, adding a quiet sophistication.",
  "It’s engineered for resilience, standing up to routine wear without fading.",
  "The shape is thoughtfully designed, providing a subtle statement.",
  "The construction feels solid, offering peace of mind with each wear.",
  "It fits comfortably, adapting to the contours of the wearer.",
  "The subtle sheen remains vibrant, resisting the test of time.",
  "It's crafted to feel light, yet surprisingly sturdy.",
  "Designed for versatility, it complements a range of styles and occasions.",
  "The piece balances elegance and everyday practicality with ease.",
  "The finish is smooth, maintaining its allure through daily activities.",
  "It feels like a natural extension of personal style, never imposing.",
  "Built for long-term wear, it keeps its polished surface intact.",
  "The design exudes understated confidence, fitting seamlessly into any wardrobe.",
  "It's designed to be worn with confidence, no matter how busy the day.",
  "Every detail radiates quality, ensuring it remains a cherished part of any collection.",
  "The silhouette offers an elegant balance between form and function.",
  "It's crafted to be light yet resilient, meeting the demands of daily life.",
  "The gentle shine adds a subtle sophistication that never overstays.",
  "It's engineered for comfort, allowing continuous wear without irritation.",
  "The design is thoughtfully simple, yet it holds a lasting allure.",
  "The construction feels robust, promising lasting presence in any setting.",
  "Delicately balanced, it feels natural and secure during everyday wear.",
  "The subtle brilliance captures attention without overwhelming the senses.",
  "The piece offers a quiet confidence, adapting effortlessly to every moment.",
];
